resource_group_name = "DevApp"
EnvironmentTag      = "DEV"
prefix              = "GabeApp"
location            = "East US"
computer_name       = "myserver"
admin_username      = "testadmin"
admin_password      = "Password1234!"
address_space       = ["10.0.0.0/16"]
address_prefixes    = ["10.0.2.0/24"]
private_ip_address  = "10.0.2.10"
